let set= new Set();
set.add('Priyasha')
set.add('Priyasha')
set.add(function addition (a,b){return a+b})
set.add(function addition (a,b){return a+b})
set.add(1010)
set.add(1010)
// set.add({})
set.add([1,2])
set.add([1,2])
set.add(undefined)
console.log(set)
set.add(null)
set.add(null)
set.add(undefined)
//console.log(addtion(34+34))
set.add('*')
set.add('*')
set.add(true)
set.add(true)
console.log(set)